import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

/// Loads and caches static resources (CSS, JS, HTML templates) from the resources directory.
class ResourceLoader {
  final String _htmlTemplate;
  final String _css;
  final String _js;
  final bool _useMinified;
  final String _resourcesDir;

  ResourceLoader._({
    required String htmlTemplate,
    required String css,
    required String js,
    required bool useMinified,
    required String resourcesDir,
  }) : _htmlTemplate = htmlTemplate,
       _css = css,
       _js = js,
       _useMinified = useMinified,
       _resourcesDir = resourcesDir;

  /// Finds the resources directory by resolving the dash package location.
  ///
  /// This works in all scenarios:
  /// - Running from dash project root (development)
  /// - Running from a project with dash as a path dependency
  /// - Running from a project with dash installed from pub.dev
  ///
  /// Returns the path to the resources directory, or null if not found.
  static Future<String?> _findResourcesDir() async {
    // First, try to resolve from package_config.json
    final packageRoot = await _resolveDashPackageRoot();
    if (packageRoot != null) {
      final resourcesDir = Directory(p.join(packageRoot, 'resources'));
      if (await resourcesDir.exists()) {
        return resourcesDir.path;
      }
    }

    // Fallback: check if we're running from dash project root
    final localResources = Directory('resources');
    if (await localResources.exists()) {
      return 'resources';
    }

    return null;
  }

  /// Resolves the root directory of the dash package by reading package_config.json.
  ///
  /// The package_config.json file is generated by `dart pub get` and contains
  /// the resolved locations of all dependencies. This works for both:
  /// - Path dependencies (relative paths like `../../`)
  /// - Pub.dev packages (file:// URIs to .pub-cache)
  static Future<String?> _resolveDashPackageRoot() async {
    // Look for package_config.json in standard locations
    final configPaths = ['.dart_tool/package_config.json'];

    for (final configPath in configPaths) {
      final configFile = File(configPath);
      if (!await configFile.exists()) continue;

      try {
        final content = jsonDecode(await configFile.readAsString()) as Map<String, dynamic>;
        final packages = content['packages'] as List<dynamic>?;
        if (packages == null) continue;

        for (final pkg in packages) {
          if (pkg['name'] != 'dash') continue;

          final rootUri = pkg['rootUri'] as String?;
          if (rootUri == null) continue;

          // Resolve the root URI relative to the config file location
          final configDir = configFile.parent.absolute;

          Uri resolvedRoot;
          if (rootUri.startsWith('file://')) {
            // Absolute file URI (pub.dev package in .pub-cache)
            resolvedRoot = Uri.parse(rootUri);
          } else {
            // Relative path (path dependency)
            resolvedRoot = Uri.directory(p.normalize(p.join(configDir.path, rootUri)));
          }

          final packageRoot = Directory.fromUri(resolvedRoot);
          if (await packageRoot.exists()) {
            return packageRoot.path;
          }
        }
      } catch (e) {
        // Continue to next config path on parse error
        continue;
      }
    }

    return null;
  }

  /// Initializes and loads all resources from disk.
  static Future<ResourceLoader> initialize() async {
    final useMinified = Platform.environment['DASH_ENV'] == 'production';

    final resourcesDir = await _findResourcesDir();
    if (resourcesDir == null) {
      throw StateError(
        'Could not find dash resources directory. '
        'Make sure you have run `dart pub get` and that the dash package '
        'contains a resources/ directory at its root.',
      );
    }

    final htmlTemplate = await _loadHtmlTemplate(resourcesDir);
    final css = await _loadCss(resourcesDir, useMinified);
    final js = await _loadAppJs(resourcesDir, useMinified);

    return ResourceLoader._(
      htmlTemplate: htmlTemplate,
      css: css,
      js: js,
      useMinified: useMinified,
      resourcesDir: resourcesDir,
    );
  }

  /// Loads the HTML template.
  static Future<String> _loadHtmlTemplate(String resourcesDir) async {
    final file = File('$resourcesDir/index.html');
    return await file.readAsString();
  }

  /// Loads the main CSS file.
  static Future<String> _loadCss(String resourcesDir, bool useMinified) async {
    final cssPath = useMinified ? '$resourcesDir/dist/css/dash.min.css' : '$resourcesDir/dist/css/dash.css';

    final file = File(cssPath);
    if (await file.exists()) {
      return await file.readAsString();
    }

    print('⚠️  CSS file not found at $cssPath - minified: $useMinified');
    return '';
  }

  /// Loads the main application JavaScript.
  static Future<String> _loadAppJs(String resourcesDir, bool useMinified) async {
    final jsPath = useMinified ? '$resourcesDir/dist/js/app.min.js' : '$resourcesDir/dist/js/app.js';

    final file = File(jsPath);
    if (await file.exists()) {
      return await file.readAsString();
    }

    print('⚠️  JS file not found at $jsPath - minified: $useMinified');
    return '';
  }

  /// Renders an HTML template with the given variables.
  ///
  /// [basePath] is the panel's base path (e.g., '/admin') used to construct
  /// static asset URLs.
  ///
  /// [pageHeadAssets] and [pageBodyAssets] are optional page-specific assets
  /// that get injected into the head and body sections respectively.
  String renderTemplate({
    required String title,
    required String body,
    String basePath = '/admin',
    String pageHeadAssets = '',
    String pageBodyAssets = '',
  }) {
    // Use static file serving for CSS and JS
    final cssFile = _useMinified ? 'dash.min.css' : 'dash.css';
    final jsFile = _useMinified ? 'app.min.js' : 'app.js';

    // In development, also add Tailwind CDN for full utility access
    final styles = _useMinified
        ? '<link rel="stylesheet" href="$basePath/assets/css/$cssFile">'
        : '<script src="https://cdn.tailwindcss.com"></script>'
              '<link rel="stylesheet" href="$basePath/assets/css/$cssFile">';

    final scripts = '<script src="$basePath/assets/js/$jsFile"></script>';

    return _htmlTemplate
        .replaceAll('@title', title)
        .replaceAll('@styles', styles)
        .replaceAll('@scripts', scripts)
        .replaceAll('@pageHeadAssets', pageHeadAssets)
        .replaceAll('@pageBodyAssets', pageBodyAssets)
        .replaceAll('@basePath', basePath)
        .replaceAll('@body', body);
  }

  /// Gets the loaded CSS content.
  String get css => _css;

  /// Gets the loaded JS content.
  String get js => _js;

  /// Gets the HTML template.
  String get htmlTemplate => _htmlTemplate;

  /// Whether production assets are being used.
  bool get isProduction => _useMinified;

  /// Gets the absolute path to the resources directory.
  String get resourcesDir => p.absolute(_resourcesDir);

  /// Gets the path to the images directory.
  String get imagesDir => p.join(resourcesDir, 'img');

  /// Gets the path to the dist directory (for built CSS/JS).
  String get distDir => p.join(resourcesDir, 'dist');
}
